### ISSUE TITLE
subprocess.CalledProcessError: Command 'java -jar ASP/sparc.jar ASP/learner.sp -A' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by hccz95** [hharithaki/HAAHT#1]
I tried your code but met a issue.
Would you like to give more details about the OS and other configurations you used?

```
(temp_env) kk@kk:/home/Document/hucong/HAAHT/Code$ python fortattack.py --test
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['/home/kk/.conda/envs/temp_env/lib/python3.6/site-packages/javabridge/jars/rhino-1.7R4.jar', '/home/kk/.conda/envs/temp_env/lib/python3.6/site-packages/javabridge/jars/runnablequeue.jar', '/home/kk/.conda/envs/temp_env/lib/python3.6/site-packages/javabridge/jars/cpython.jar', '/home/kk/.conda/envs/temp_env/lib/python3.6/site-packages/weka/lib/weka.jar', '/home/kk/.conda/envs/temp_env/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support disabled
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by weka.core.WekaPackageClassLoaderManager (file:/home/kk/.conda/envs/temp_env/lib/python3.6/site-packages/weka/lib/weka.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of weka.core.WekaPackageClassLoaderManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SPARC  V2.57
program translated
Clingo not found. You should have clingo or clingo.exe available from your path or current folder.
Exception in thread "main" java.lang.NullPointerException
        at solving.Runner.getDisplayPredicates(Unknown Source)
        at solving.Runner.outputAnswerSets(Unknown Source)
        at parser.SparcTranslator.main(Unknown Source)
Traceback (most recent call last):
  File "fortattack.py", line 59, in <module>
    m_fortattack(args)
  File "fortattack.py", line 33, in m_fortattack
    learner_actions = ad_hoc.learner(obs, alive_ag, previous_action, step)
  File "/home/Document/hucong/HAAHT/Code/ad_hoc.py", line 39, in learner
    answer_list = runASPLearner(obs, input, next_terms, facing_terms, goal_term, goal_guard, pre_asp_split, display_marker_index)
  File "/home/Document/hucong/HAAHT/Code/ad_hoc.py", line 258, in runASPLearner
    answer = subprocess.check_output('java -jar ASP/sparc.jar ' +asp_learner+' -A',shell=True)
  File "/home/kk/.conda/envs/temp_env/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/kk/.conda/envs/temp_env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'java -jar ASP/sparc.jar ASP/learner.sp -A' returned non-zero exit status 1.
```

**Comment by hharithaki** [comment]
The code is tested with Linux OS. Have you installed clingo before running the code?

**Comment by hccz95** [comment]
> The code is tested with Linux OS. Have you installed clingo before running the code?

No, I successfully run your code after installing clingo. Thanks!!
